# tamtam inspected 2026-05-21
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/pnpm-lock.yaml"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

nextjs:
  - changed-files:
      - any-glob-to-any-file:
          - "app/**"
          - "components/**"
          - "lib/**"
          - "next.config.ts"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "__tests__/**"
