repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace # This hook trims trailing whitespace.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: check-json # This hook checks json files for parsable syntax.
      - id: check-yaml # This hook checks yaml files for parsable syntax.
      - id: check-added-large-files
        args: ['--maxkb=15000']
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
