// tamtam inspected 2026-05-21
export const DEFAULT_EPG_URL =
  "https://epgshare01.online/epgshare01/epg_ripper_PL1.xml.gz";

export const EPG_PRESETS: { label: string; url: string }[] = [
  { label: "Poland (broadcast)",         url: "https://epgshare01.online/epgshare01/epg_ripper_PL1.xml.gz" },
  { label: "UK (broadcast)",             url: "https://epgshare01.online/epgshare01/epg_ripper_UK1.xml.gz" },
  { label: "Germany (broadcast)",        url: "https://epgshare01.online/epgshare01/epg_ripper_DE1.xml.gz" },
  { label: "France (broadcast)",         url: "https://epgshare01.online/epgshare01/epg_ripper_FR1.xml.gz" },
  { label: "Italy (broadcast)",          url: "https://epgshare01.online/epgshare01/epg_ripper_IT1.xml.gz" },
  { label: "Spain (broadcast)",          url: "https://epgshare01.online/epgshare01/epg_ripper_ES1.xml.gz" },
  { label: "Netherlands (broadcast)",    url: "https://epgshare01.online/epgshare01/epg_ripper_NL1.xml.gz" },
  { label: "Sweden (broadcast)",         url: "https://epgshare01.online/epgshare01/epg_ripper_SE1.xml.gz" },
  { label: "Norway (broadcast)",         url: "https://epgshare01.online/epgshare01/epg_ripper_NO1.xml.gz" },
  { label: "Denmark (broadcast)",        url: "https://epgshare01.online/epgshare01/epg_ripper_DK1.xml.gz" },
  { label: "Finland (broadcast)",        url: "https://epgshare01.online/epgshare01/epg_ripper_FI1.xml.gz" },
  { label: "Czech Republic (broadcast)", url: "https://epgshare01.online/epgshare01/epg_ripper_CZ1.xml.gz" },
  { label: "Slovakia (broadcast)",       url: "https://epgshare01.online/epgshare01/epg_ripper_SK1.xml.gz" },
  { label: "Hungary (broadcast)",        url: "https://epgshare01.online/epgshare01/epg_ripper_HU1.xml.gz" },
  { label: "Romania (broadcast)",        url: "https://epgshare01.online/epgshare01/epg_ripper_RO1.xml.gz" },
  { label: "Bulgaria (broadcast)",       url: "https://epgshare01.online/epgshare01/epg_ripper_BG1.xml.gz" },
  { label: "Portugal (broadcast)",       url: "https://epgshare01.online/epgshare01/epg_ripper_PT1.xml.gz" },
  { label: "Greece (broadcast)",         url: "https://epgshare01.online/epgshare01/epg_ripper_GR1.xml.gz" },
  { label: "USA (broadcast)",            url: "https://epgshare01.online/epgshare01/epg_ripper_US1.xml.gz" },
  { label: "Australia (broadcast)",      url: "https://epgshare01.online/epgshare01/epg_ripper_AU1.xml.gz" },
  { label: "Germany (Samsung TV+)",    url: "https://i.mjh.nz/SamsungTVPlus/de.xml.gz" },
  { label: "UK (Samsung TV+)",         url: "https://i.mjh.nz/SamsungTVPlus/gb.xml.gz" },
  { label: "France (Samsung TV+)",     url: "https://i.mjh.nz/SamsungTVPlus/fr.xml.gz" },
  { label: "USA (Samsung TV+)",        url: "https://i.mjh.nz/SamsungTVPlus/us.xml.gz" },
  { label: "All (Samsung TV+)",        url: "https://i.mjh.nz/SamsungTVPlus/all.xml.gz" },
  { label: "Germany (Pluto TV)",       url: "https://i.mjh.nz/PlutoTV/de.xml.gz" },
  { label: "UK (Pluto TV)",            url: "https://i.mjh.nz/PlutoTV/gb.xml.gz" },
  { label: "France (Pluto TV)",        url: "https://i.mjh.nz/PlutoTV/fr.xml.gz" },
  { label: "USA (Pluto TV)",           url: "https://i.mjh.nz/PlutoTV/us.xml.gz" },
  { label: "All (Pluto TV)",           url: "https://i.mjh.nz/PlutoTV/all.xml.gz" },
];
