name: Lint

on:
  push:

jobs:
  build:
      name: Lint and Test
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: Lint
          uses: gabriel-milan/action-pylint@v1
          with:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub token
            path: "./*.py" # Glob pattern for files to lint
            fail: true # Fail the action if pylint errors are found
            pr-message: true # Send a PR message if pylint errors are found
