on:
  push:
    branches:
      - master

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          token: ${{ secrets.CUSTOM_PAT_WITH_WORKFLOWS_ACCESS }}
